broken-link-checker:
  exclude-directories:
    - .git/
    - projects/
  skip-urls:
      - https://download.docker.com/linux/ubuntu/gpg
      - https://github.com/docker/compose/releases/download/1.22.0/docker-compose
